"""
Project Euler - Problem 2
Date: 2026-03-11
Link: https://projecteuler.net/problem=2
"""

# Problem Description:
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with $1$ and $2$, the first $10$ terms will be: $$1,
# 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$ By considering the terms in the
# Fibonacci sequence whose values do not exceed four million, find the sum of
# the even-valued terms.


def solve():
    """TODO: Implement solution."""
    pass


if __name__ == "__main__":
    result = solve()
    print(f"Answer: {result}")
